### ISSUE TITLE
Starting ledgerble does nothing

### ISSUE THREAD

**Issue by MartyLake** [sbridges/ledgerble#1]
Hey,

I'm trying to test ledgerble in WSL, and it does nothing.

```
$ ledgerble
$ <cursor is here, nothing is written anywhere>
```

Do you have any idea how to diagnose further ? Maybe I should try to install npm on windows directly ?

**Comment by sbridges** [comment]
Probably easier to install npm on windows directly.

Ledgerble is an electron application, some searches show:

https://stackoverflow.com/questions/49936910/unable-to-run-electron-quick-start-in-wsl
https://github.com/electron-userland/electron-prebuilt/issues/260

**Comment by MartyLake** [comment]
Hey, thanks for your swift answer. Yes of course, I though it was a webserver that I could access with my browser.

So after installing npm on windows using chocolatey and installing ledgerble, I have the following error when launching:

```
C:\Users\MartyLake>ledgerble
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)[39m
[90m    at onErrorNT (internal/child_process.js:456:16)[39m
[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)[39m
Emitted 'error' event on ChildProcess instance at:
[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)[39m
[90m    at onErrorNT (internal/child_process.js:456:16)[39m
[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)[39m {
  errno: [32m'ENOENT'[39m,
  code: [32m'ENOENT'[39m,
  syscall: [32m'spawn npm'[39m,
  path: [32m'npm'[39m,
  spawnargs: [
    [32m'start'[39m,
    [32m'--prefix'[39m,
    [32m'C:\\Users\\MartyLake\\AppData\\Roaming\\npm\\node_modules\\ledgerble'[39m
  ]
}
```

**Comment by sbridges** [comment]
is npm on your path?  you can test this by typing npm --version in the console.

**Comment by MartyLake** [comment]
Yes it is

```
>npm --version
6.11.3
```

**Comment by sbridges** [comment]
sorry, it's hard for me to debug this because I don't have access to a windows machine.  I've tried packaging ledgerble for windows, could you see if this works for you,

https://github.com/sbridges/ledgerble/releases/download/v0.0.6/ledgerble-win-0.0.6.zip

**Comment by MartyLake** [comment]
I understand !
So the same error displays, but now the GUI opens. Unfortunately no data is ever displayed even after loading my file. Only the structure of the program, as if I had loaded an empty file.

![ledgerble error](https://user-images.githubusercontent.com/1246794/67639391-7a0c2800-f8ef-11e9-93b1-7195552c9015.PNG)
![ledgerble starts but empty windowPNG](https://user-images.githubusercontent.com/1246794/67639392-7a0c2800-f8ef-11e9-9999-622d7c4ccbff.PNG)

**Comment by sbridges** [comment]
I think its due to this, https://github.com/electron/electron/issues/10451

the function is undefined on windows

**Comment by sbridges** [comment]
could you try 0.0.8 and see if it fixes it

**Comment by MartyLake** [comment]
When installing from npm, it does not start :

```
$ npm install -g ledgerble
C:\Users\MartyLake\AppData\Roaming\npm\ledgerble -> C:\Users\MartyLake\AppData\Roaming\npm\node_modules\ledgerble\ledgerble.js

> electron@6.1.2 postinstall C:\Users\MartyLake\AppData\Roaming\npm\node_modules\ledgerble\node_modules\electron
> node install.js

Downloading tmp-13424-1-SHASUMS256.txt-6.1.2
[============================================>] 100.0% of 5.15 kB (5.15 kB/s)
+ ledgerble@0.0.8
updated 4 packages in 29.591s

$ ledgerble
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [
    'start',
    '--prefix',
    'C:\\Users\\MartyLake\\AppData\\Roaming\\npm\\node_modules\\ledgerble'
  ]
}
```

**Comment by MartyLake** [comment]
The dist version (from github release) works ! Thanks you very much for your help ! You can close it if you want. Maybe adding some notes on the README about using the dist version instead of npm ?

**Comment by sbridges** [comment]
thanks, updated
