### ISSUE TITLE
Can't select any journal file

### ISSUE THREAD

**Issue by varac** [sbridges/ledgerble#4]
I installed lederble today using `npm install ledgerble`. After starting, I see the notice `Use the Files menu to select one or more journal files.`, but I cannot since the `Files` menu doesn't contain any other option than `Quit`, see this screenshot: 
![IMG_20200504_113615](https://user-images.githubusercontent.com/488213/80953734-65f43680-8dfc-11ea-88b0-f23a9075f6a7.jpg)

**Comment by varac** [comment]
It would be also great if you could pass a journal filename on startup, i.e. `lederble -f ~/.hledger.journal`

**Comment by sbridges** [comment]
There is a files tab on the ledgerble window with a drop down, its  right next to the Options Tab does that work?

**Comment by sbridges** [comment]
I think this is user error, the files tab lets you select files.  The screen shot shows the files menu which does now work.

**Comment by varac** [comment]
Right, I was confused by the two different "Files" dialogs.
